// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import MealFieldsController from "./meal_fields_controller"
import DisplayController from "./display_controller"
import InviteController from "./invite_controller"
import TrayItemsController from "./tray_items_controller"
application.register("meal-fields", MealFieldsController)
application.register("display", DisplayController)
application.register("invite", InviteController)
application.register("tray-items", TrayItemsController)
